/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consulta;

import java.awt.Color;
import java.util.LinkedList;

/**
 *
 * @author USER
 */
public class Ventana_de_Consulta extends javax.swing.JFrame {
    
    LinkedList<Establecimiento> lista_Establecimientos;
    /**
     * Creates new form Ventana_de_Inicio
     */
    public Ventana_de_Consulta() {
        initComponents();
        lista_Establecimientos = new LinkedList();
        lista_Establecimientos.add(new Establecimiento("CENTRO DE SALUD ESPIGA DE ORO", "Calle Rumiñahui y Pululahua", 
                "Desconocido", 1000, 650, 350, "022425887"));
        lista_Establecimientos.add(new Establecimiento("CENTRO DE SALUD TABACUNDO", "CABO FRANCISCO FALCÓN Y VIRGILIO VALENCIA", 
                "Desconocido", 1100, 450, 600, "022742639"));
        lista_Establecimientos.add(new Establecimiento("CENTRO DE SALUD ALOASI", "ANDRES OREST Y SUCRE", 
                "Desconocido", 1500, 500, 700, "022869224"));
        lista_Establecimientos.add(new Establecimiento("CENTRO DE SALUD MINDO", "CALLE SIXTO DURAN BALLEN Y QUITO", 
                "Desconocido", 2000, 800, 900, "026859334"));
    }
    
    private String obtener_info(LinkedList<Establecimiento> establecimientos, String texto_buscado){
        String informacion_salida;
        informacion_salida = "No se encontro informacion.";
        for (Establecimiento estab1 : establecimientos){
            if (estab1.getNombre_establecimiento().toLowerCase().equals(texto_buscado.toLowerCase())){
                informacion_salida = "Esta informacion es de prueba solo los nombres\ny direcciones son reales.\n\n"
                        + "Nombre del establecimiento: "+ estab1.getNombre_establecimiento() +"\n\n"
                        + "Direccion del establecimiento: " +estab1.getDireccion()+ "\n\n"
                        + "Persona Responable: "+ estab1.getNombre_encargado()+ "\n\n"
                        + "Dosis de vacunas entregadas: " + estab1.getDosis_recibida() + "\n\n"
                        + "Dosis de vacunas aplicadas: " + estab1.getDosis_aplicada() + "\n\n"
                        + "Dosis de vacunas  restante: " + estab1.getDosis_restante() + "\n\n"
                        + "Numero de contacto: " + estab1.getNumero_contaco() + "\n";
            }
        }
        return informacion_salida;
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        texto_buscar_establecimiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_texto_salida_informacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        texto_buscar_establecimiento.setForeground(new java.awt.Color(153, 153, 153));
        texto_buscar_establecimiento.setText("Ingrese nombre de establecimiento");
        texto_buscar_establecimiento.setToolTipText("");
        texto_buscar_establecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto_buscar_establecimientoMouseClicked(evt);
            }
        });
        texto_buscar_establecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_buscar_establecimientoActionPerformed(evt);
            }
        });

        area_texto_salida_informacion.setEditable(false);
        area_texto_salida_informacion.setColumns(20);
        area_texto_salida_informacion.setRows(5);
        jScrollPane1.setViewportView(area_texto_salida_informacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(texto_buscar_establecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(texto_buscar_establecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void texto_buscar_establecimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_buscar_establecimientoMouseClicked
        if("Ingrese nombre de establecimiento".equals(texto_buscar_establecimiento.getText())){
        texto_buscar_establecimiento.setText("");
        texto_buscar_establecimiento.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_texto_buscar_establecimientoMouseClicked

    private void texto_buscar_establecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_buscar_establecimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_buscar_establecimientoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        area_texto_salida_informacion.setText("");
        String texto_buscado, informacion_salida;
        texto_buscado = texto_buscar_establecimiento.getText();
        informacion_salida =obtener_info(lista_Establecimientos, texto_buscado);
        area_texto_salida_informacion.append(informacion_salida);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_de_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_de_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_de_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_de_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_de_Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_texto_salida_informacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField texto_buscar_establecimiento;
    // End of variables declaration//GEN-END:variables
}
